export const arts = [
    {
        "id": 1,
        "mood": "alone",
        "keywords": "unparalleled solely unique solitary lonely lone unequaled unequalled unaccompanied solo entirely alone only exclusively",
        // "filepath": "/assets/images/alone0.jpeg",
        "filepath": "assets/images/alone0.jpeg",
        "quote": '',
    },
    {
        "id": 2,
        "mood": "calm",
        "keywords": "composure tranquilize equanimity steady serene calm_air calmness simmer_down lull becalm sedate tranquil quieten cool_off chill_out unagitated tranquillize settle_down calm_down tranquillise cool_it calm still quiet",
        "filepath": "/assets/images/calm0.jpeg",
        "quote": '',
    },
    {
        "id": 3,
        "mood": "confident",
        "keywords": "positive surefooted confident positive empowerment convinced sure-footed",
        "filepath": "/assets/images/confident0.jpeg",
        "quote": '',
    },
    {
        "id": 4,
        "mood": "confident",
        "keywords": "positive surefooted confident positive empowerment convinced sure-footed",
        "filepath": "/assets/images/confident1.jpeg",
        "quote": '',
    },
    {
        "id": 5,
        "mood": "creative",
        "keywords": "creative ideas originative",
        "filepath": "/assets/images/creative0.jpeg",
        "quote": '',
    },
    {
        "id": 6,
        "mood": "creative",
        "keywords": "creative ideas originative",
        "filepath": "/assets/images/creative1.jpeg",
        "quote": '',
    },
    {
        "id": 7,
        "mood": "curious",
        "keywords": "curious rum odd queer peculiar singular rummy funny",
        "filepath": "/assets/images/curious0.jpeg",
        "quote": '',
    },
    {
        "id": 8,
        "mood": "curious",
        "keywords": "curious rum odd queer peculiar singular rummy funny",
        "filepath": "/assets/images/curious1.jpeg",
        "quote": '',
    },
    {
        "id": 9,
        "mood": "curious",
        "keywords": "curious rum odd queer peculiar singular rummy funny",
        "filepath": "/assets/images/curious2.jpeg",
        "quote": '',
    },
    {
        "id": 10,
        "mood": "energized",
        "keywords": "stimulate perk_up excite energise arouse energize brace",
        "filepath": "/assets/images/energized0.jpeg",
        "quote": '',
    },
    {
        "id": 11,
        "mood": "foggy",
        "keywords": "stuporous blurred fuzzy bleary misty hazy blurry foggy dazed muzzy fogged brumous logy groggy confusion thoughts",
        "filepath": "/assets/images/foggy0.jpeg",
        "quote": '',
    },
    {
        "id": 12,
        "mood": "free",
        "keywords": "devoid loose unloosen gratuitous dislodge liberal detached relieve unloose spare disengage unfreeze resign costless unblock liberate justify absolve gratis destitute relinquish free_people disembarrass barren release innocent rid give_up free complimentary discharge exempt",
        "filepath": "/assets/images/free0.jpeg",
        "quote": '',
    },
    {
        "id": 13,
        "mood": "happy",
        "keywords": "felicitous well-chosen happy glad",
        "filepath": "/assets/images/happy0.jpeg",
        "quote": '',
    },
    {
        "id": 14,
        "mood": "happy",
        "keywords": "felicitous well-chosen happy glad",
        "filepath": "/assets/images/happy1.jpeg",
        "quote": '',
    },
    {
        "id": 15,
        "mood": "hopeful",
        "keywords": "aspirer wannabee promising wannabe aspirant hopeful bright",
        "filepath": "/assets/images/hopeful0.jpeg",
        "quote": '',
    },
    {
        "id": 16,
        "mood": "joyful",
        "keywords": "jubilant gleeful elated joyful joy",
        "filepath": "/assets/images/joyful0.jpeg",
        "quote": '',
    },
    {
        "id": 17,
        "mood": "joyful",
        "keywords": "jubilant gleeful elated joyful joy",
        "filepath": "/assets/images/joyful1.jpg",
        "quote": '',
    },
    {
        "id": 20,
        "mood": "lazy",
        "keywords": "lazy slothful faineant work-shy indolent otiose",
        "filepath": "/assets/images/lazy0.jpeg",
        "quote": '',
    },
    {
        "id": 21,
        "mood": "melancholy",
        "keywords": "black_bile melancholic somber melancholy sombre sad",
        "filepath": "/assets/images/melancholy0.jpeg",
        "quote": '',
    },
    {
        "id": 22,
        "mood": "passionate",
        "keywords": "together inspired passionate passion love",
        "filepath": "/assets/images/passionate0.jpeg",
        "quote": '',
    },
    {
        "id": 23,
        "mood": "passionate",
        "keywords": "together inspired passionate passion love",
        "filepath": "/assets/images/passionate1.jpeg",
        "quote": '',
    },
    {
        "id": 24,
        "mood": "reflective",
        "keywords": "meditative meditate brooding pensive broody pondering contemplative ruminative musing reflective",
        "filepath": "/assets/images/reflective0.jpeg",
        "quote": '',
    },
    {
        "id": 25,
        "mood": "thoughtful",
        "keywords": "paying_attention heedful attentive serious-minded thoughtful",
        "filepath": "/assets/images/thoughtful0.jpeg",
        "quote": '',
    }
]